-- 棋牌室开单系统 · Supabase (PostgreSQL) 初始化
-- 在 Supabase Dashboard → SQL Editor 执行，或运行 code/backend: python -m scripts.apply_schema

-- ---------------------------------------------------------------------------
-- 枚举类型
-- ---------------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE user_role AS ENUM ('CASHIER', 'MANAGER', 'SHAREHOLDER', 'ADMIN');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE order_status AS ENUM ('OPEN', 'CLOSED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- ---------------------------------------------------------------------------
-- 通用：updated_at 自动更新
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP(3);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- 一桌一单：触发器函数
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_biz_order_one_open_insert_fn()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'OPEN' AND EXISTS (
    SELECT 1 FROM biz_order o
    WHERE o.table_id = NEW.table_id AND o.status = 'OPEN'
  ) THEN
    RAISE EXCEPTION '该桌台已有进行中订单，请先清台';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION trg_biz_order_one_open_update_fn()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'OPEN' AND NEW.table_id <> OLD.table_id AND EXISTS (
    SELECT 1 FROM biz_order o
    WHERE o.table_id = NEW.table_id AND o.status = 'OPEN' AND o.id <> NEW.id
  ) THEN
    RAISE EXCEPTION '目标桌台已有进行中订单';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- 删表（开发初始化；生产已有数据勿直接重跑）
-- 注意：勿在表不存在时 DROP TRIGGER ON biz_order，会报 42P01；
--       CASCADE 删表时会一并移除触发器。
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS biz_order CASCADE;
DROP TABLE IF EXISTS price_change_log CASCADE;
DROP TABLE IF EXISTS room_table CASCADE;
DROP TABLE IF EXISTS sys_store_config CASCADE;
DROP TABLE IF EXISTS sys_user CASCADE;

-- ---------------------------------------------------------------------------
-- 1. 用户与角色
-- ---------------------------------------------------------------------------
CREATE TABLE sys_user (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(64)  NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  display_name  VARCHAR(64)  NOT NULL DEFAULT '',
  role          user_role    NOT NULL,
  is_enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT uk_username UNIQUE (username)
);

CREATE INDEX idx_sys_user_role_enabled ON sys_user (role, is_enabled);

CREATE TRIGGER trg_sys_user_updated_at
  BEFORE UPDATE ON sys_user
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 2. 门店全局配置（单行）
-- ---------------------------------------------------------------------------
CREATE TABLE sys_store_config (
  id                         SMALLINT     NOT NULL DEFAULT 1 PRIMARY KEY,
  base_price                 NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  enable_timing              BOOLEAN      NOT NULL DEFAULT FALSE,
  billing_unit_minutes       INTEGER      NOT NULL DEFAULT 60,
  min_billing_units          INTEGER      NOT NULL DEFAULT 1,
  cashier_allow_custom_price BOOLEAN      NOT NULL DEFAULT TRUE,
  cashier_allow_export       BOOLEAN      NOT NULL DEFAULT FALSE,
  cashier_report_months      INTEGER      NULL,
  admin_report_days          INTEGER      NULL,
  updated_by                 BIGINT       NULL,
  updated_at                 TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT chk_store_config_singleton CHECK (id = 1)
);

CREATE TRIGGER trg_sys_store_config_updated_at
  BEFORE UPDATE ON sys_store_config
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 3. 基准价变更记录
-- ---------------------------------------------------------------------------
CREATE TABLE price_change_log (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_price  NUMERIC(10, 2) NOT NULL,
  new_price  NUMERIC(10, 2) NOT NULL,
  changed_by BIGINT         NOT NULL REFERENCES sys_user (id),
  created_at TIMESTAMP(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE INDEX idx_price_change_log_created_at ON price_change_log (created_at);

-- ---------------------------------------------------------------------------
-- 4. 台位
-- ---------------------------------------------------------------------------
CREATE TABLE room_table (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(64)  NOT NULL,
  sort_order INTEGER      NOT NULL DEFAULT 0,
  is_enabled BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT uk_room_table_name UNIQUE (name)
);

CREATE INDEX idx_room_table_enabled_sort ON room_table (is_enabled, sort_order);

CREATE TRIGGER trg_room_table_updated_at
  BEFORE UPDATE ON room_table
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 5. 开单订单
-- ---------------------------------------------------------------------------
CREATE TABLE biz_order (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no        VARCHAR(32)    NOT NULL,
  table_id        BIGINT         NOT NULL REFERENCES room_table (id),
  base_price      NUMERIC(10, 2) NOT NULL,
  actual_price    NUMERIC(10, 2) NOT NULL,
  billing_minutes INTEGER        NULL,
  status          order_status   NOT NULL DEFAULT 'OPEN',
  remark          VARCHAR(500)   NULL,
  opened_by       BIGINT         NOT NULL REFERENCES sys_user (id),
  opened_at       TIMESTAMP(3)   NOT NULL,
  closed_by       BIGINT         NULL REFERENCES sys_user (id),
  closed_at       TIMESTAMP(3)   NULL,
  created_at      TIMESTAMP(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at      TIMESTAMP(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT uk_order_no UNIQUE (order_no)
);

CREATE INDEX idx_biz_order_table_status ON biz_order (table_id, status);
CREATE INDEX idx_biz_order_opened_by_opened_at ON biz_order (opened_by, opened_at);
CREATE INDEX idx_biz_order_status_closed_at ON biz_order (status, closed_at);
CREATE INDEX idx_biz_order_opened_at ON biz_order (opened_at);

CREATE TRIGGER trg_biz_order_updated_at
  BEFORE UPDATE ON biz_order
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_biz_order_one_open_insert
  BEFORE INSERT ON biz_order
  FOR EACH ROW EXECUTE FUNCTION trg_biz_order_one_open_insert_fn();

CREATE TRIGGER trg_biz_order_one_open_update
  BEFORE UPDATE ON biz_order
  FOR EACH ROW EXECUTE FUNCTION trg_biz_order_one_open_update_fn();

-- ---------------------------------------------------------------------------
-- 6. RLS：禁止通过 Supabase Data API 匿名访问（后端直连 postgres 用户不受影响）
-- ---------------------------------------------------------------------------
ALTER TABLE sys_user ENABLE ROW LEVEL SECURITY;
ALTER TABLE sys_store_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE price_change_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_table ENABLE ROW LEVEL SECURITY;
ALTER TABLE biz_order ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- 7. 初始数据
-- ---------------------------------------------------------------------------
INSERT INTO sys_store_config (
  id, base_price, enable_timing, billing_unit_minutes, min_billing_units,
  cashier_allow_custom_price, cashier_allow_export, cashier_report_months, admin_report_days
) VALUES (1, 100.00, FALSE, 60, 1, TRUE, FALSE, 3, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO room_table (name, sort_order, is_enabled) VALUES
  ('A01', 10, TRUE),
  ('A02', 20, TRUE),
  ('A03', 30, TRUE),
  ('B01', 40, TRUE),
  ('B02', 50, TRUE)
ON CONFLICT (name) DO NOTHING;
